### ISSUE TITLE
Remove/reduce underscore dependency

### ISSUE THREAD

**Issue by soumak77** [personality-insights/trait-names#10]
This library (and others) only use 3 method from `underscore`, yet the entire library is included.  Either the dependencies should be updated to only include the code for necessary methods or the methods should be replaced with native javascript to reduce the size of the package.

**Comment by soumak77** [comment]
I don't know if underscore provides submodules.  Perhaps you should consider switching to use lodash which offers the ability to import only the functions you need: https://github.com/lodash/lodash#installation

**Comment by soumak77** [comment]
Guide for migrating from underscore: https://github.com/lodash/lodash/wiki/Migrating

**Comment by germanattanasio** [comment]
Fixed in 2.1.0

**Comment by soumak77** [comment]
@germanattanasio awesome thanks!  Are you planning to make the same changes to the other repositories in this repo?

**Comment by germanattanasio** [comment]
which other repo? I'm happy to merge a PR but I don't think it's a priority for me now :(

**Comment by soumak77** [comment]
@germanattanasio the follow repos need to be updated with the changes to use lodash and possibly the webpack updates as well.  It's basically a copy and paste from the changes that have already been made.  I don't have the time to do it myself now, but I'll submit a PR in the future if no one else has.

- https://github.com/personality-insights/consumption-preferences
- https://github.com/personality-insights/trait-descriptions
- https://github.com/personality-insights/text-summary
- https://github.com/personality-insights/trait-info

**Comment by germanattanasio** [comment]
That will be great
